// Catálogo canônico de material odontológico (bundlado; o backend pode atualizar em runtime).
// prices = null/ausente significa que a loja não tem o item.
// `let` + live binding: replaceCatalog() troca a referência e TODOS os consumidores
// (matcher, ProductPicker, decode) passam a ler o catálogo novo, sem refatorar imports.
export let CATALOG = [
  { id: "espelho", std: "Espelho Bucal Plano nº 5", cat: "Instrumental", kw: ["espelho", "bucal"],
    brands: [{ name: "Golgran", prices: { cremer: 14.9, surya: 13.41, speed: 15.65 } }, { name: "Genérico", prices: { cremer: 8.9, surya: 8.01, speed: 9.35 } }] },
  { id: "cabo-esp", std: "Cabo para Espelho Bucal", cat: "Instrumental", kw: ["cabo", "espelho"],
    brands: [{ name: "Golgran", prices: { cremer: 11.9, surya: 10.71, speed: 12.5 } }] },
  { id: "sonda-exp", std: "Sonda Exploradora nº 5", cat: "Instrumental", kw: ["sonda", "exploradora"],
    brands: [{ name: "Golgran", prices: { cremer: 13.5, surya: 12.15, speed: 14.18 } }] },
  { id: "sonda-per", std: "Sonda Periodontal Williams", cat: "Instrumental", kw: ["sonda", "periodontal", "milimetrada", "williams"],
    brands: [{ name: "Golgran", prices: { cremer: 22.9, surya: 20.61, speed: null } }] },
  { id: "pinca", std: "Pinça Clínica", cat: "Instrumental", kw: ["pinca", "clinica"],
    brands: [{ name: "Golgran", prices: { cremer: 16.9, surya: 15.21, speed: 17.75 } }] },
  { id: "esp-ins", std: "Espátula de Inserção nº 1 (Thompson)", cat: "Instrumental", kw: ["insercao", "thompson", "ward"],
    brands: [{ name: "Duflex", prices: { cremer: 19.9, surya: 17.91, speed: 20.89 } }] },
  { id: "esp-res", std: "Espátula para Resina (Suprafill)", cat: "Instrumental", kw: ["espatula", "suprafill"],
    brands: [{ name: "Duflex", prices: { cremer: 24.9, surya: 22.41, speed: null } }] },
  { id: "escav", std: "Escavador / Colher de Dentina nº 17", cat: "Instrumental", kw: ["escavador", "cureta", "dentina", "colher"],
    brands: [{ name: "Duflex", prices: { cremer: 18.9, surya: 17.01, speed: 19.84 } }] },
  { id: "cond", std: "Condensador de Amálgama", cat: "Instrumental", kw: ["condensador", "amalgama"],
    brands: [{ name: "Duflex", prices: { cremer: 21.9, surya: 19.71, speed: 23.0 } }] },
  { id: "toffle", std: "Porta-Matriz de Tofflemire", cat: "Instrumental", kw: ["matriz", "tofflemire"],
    brands: [{ name: "Golgran", prices: { cremer: 44.9, surya: 40.41, speed: null } }] },
  { id: "bisturi", std: "Cabo de Bisturi nº 3", cat: "Instrumental", kw: ["bisturi"],
    brands: [{ name: "ABC", prices: { cremer: 15.9, surya: 14.31, speed: 16.7 } }] },
  { id: "porta-ag", std: "Porta-Agulha Mayo-Hegar 14cm", cat: "Instrumental", kw: ["agulha", "mayo", "hegar"],
    brands: [{ name: "Golgran", prices: { cremer: 59.9, surya: null, speed: 62.9 } }] },
  { id: "tesoura", std: "Tesoura Íris Reta", cat: "Instrumental", kw: ["tesoura", "iris", "goldman"],
    brands: [{ name: "Golgran", prices: { cremer: 34.9, surya: 31.41, speed: null } }] },
  { id: "alavanca", std: "Alavanca Seldin nº 2 Reta", cat: "Instrumental", kw: ["alavanca", "seldin"],
    brands: [{ name: "Quinelato", prices: { cremer: 39.9, surya: 35.91, speed: 41.9 } }] },
  { id: "forceps", std: "Fórceps nº 150 (Adulto)", cat: "Instrumental", kw: ["forceps", "150"],
    brands: [{ name: "Quinelato", prices: { cremer: 74.9, surya: 67.41, speed: null } }] },
  { id: "molt", std: "Destaca-Periósteo Molt", cat: "Instrumental", kw: ["destaca", "periosteo", "molt", "sindesmotomo"],
    brands: [{ name: "Quinelato", prices: { cremer: 42.9, surya: 38.61, speed: 45.05 } }] },
  { id: "placa", std: "Placa de Vidro para Manipulação", cat: "Instrumental", kw: ["placa", "vidro"],
    brands: [{ name: "SS White", prices: { cremer: 19.9, surya: 17.91, speed: 20.89 } }] },
  { id: "resina", std: "Resina Composta Z350 XT (A2)", cat: "Material", kw: ["resina", "z350", "filtek"],
    brands: [{ name: "3M Filtek", prices: { cremer: 129.9, surya: 116.91, speed: 136.4 } }, { name: "FGM Opallis", prices: { cremer: 79.9, surya: 71.91, speed: 83.9 } }] },
  { id: "ionomero", std: "Ionômero de Vidro Restaurador", cat: "Material", kw: ["ionomero", "ionomero de vidro", "civ", "vidrion", "ketac", "maxxion"],
    brands: [{ name: "3M Ketac", prices: { cremer: 89.9, surya: 80.91, speed: null } }, { name: "SS White Vidrion", prices: { cremer: 44.9, surya: 40.41, speed: null } }] },
  { id: "adesivo", std: "Sistema Adesivo (Single Bond)", cat: "Material", kw: ["adesivo", "single", "bond", "ambar"],
    brands: [{ name: "3M Single Bond", prices: { cremer: 99.9, surya: 89.91, speed: null } }, { name: "FGM Ambar", prices: { cremer: 64.9, surya: 58.41, speed: null } }] },
  { id: "acido", std: "Condicionador Ácido Fosfórico 37%", cat: "Material", kw: ["acido", "condicionador", "fosforico"],
    brands: [{ name: "FGM", prices: { cremer: 14.9, surya: 13.41, speed: 15.65 } }] },
  { id: "brocas", std: "Kit de Brocas Diamantadas", cat: "Material", kw: ["broca", "brocas", "diamantada"],
    brands: [{ name: "KG Sorensen", prices: { cremer: 49.9, surya: 44.91, speed: null } }] },
  { id: "dique", std: "Lençol de Borracha / Dique (caixa)", cat: "Material", kw: ["lencol", "borracha", "dique", "isolamento"],
    brands: [{ name: "Madeitex", prices: { cremer: 34.9, surya: 31.41, speed: 36.65 } }] },
  { id: "soflex", std: "Discos de Lixa para Acabamento (kit)", cat: "Material", kw: ["disco", "discos", "lixa"],
    brands: [{ name: "3M Sof-Lex", prices: { cremer: 59.9, surya: 53.91, speed: null } }, { name: "TDV Pop On", prices: { cremer: 44.9, surya: 40.41, speed: null } }] },
  { id: "sutura", std: "Fio de Sutura Seda 4-0 (caixa)", cat: "Material", kw: ["sutura", "seda", "nylon"],
    brands: [{ name: "Shalon", prices: { cremer: 39.9, surya: 35.91, speed: 41.9 } }] },
  { id: "manequim", std: "Manequim de Dentística", cat: "Instrumental", kw: ["manequim"],
    brands: [{ name: "Pronew", prices: { cremer: null, surya: null, speed: null } }] },
  { id: "espessimetro", std: "Espessímetro Odontológico", cat: "Instrumental", kw: ["espessimetro"],
    brands: [{ name: "Ice", prices: { cremer: null, surya: null, speed: null } }] },
  { id: "moldeira-total", std: "Moldeira de Moldagem Total (kit)", cat: "Instrumental", kw: ["moldeira", "total", "totais"],
    brands: [{ name: "Bioart", prices: { cremer: 49.9, surya: 44.91, speed: 52.4 } }, { name: "Genérico", prices: { cremer: 32.9, surya: 29.61, speed: 34.55 } }] },
  { id: "moldeira-parcial", std: "Moldeira Parcial Perfurada", cat: "Instrumental", kw: ["moldeira", "parcial", "parciais"],
    brands: [{ name: "Tecnodent", prices: { cremer: 12.9, surya: 11.61, speed: 13.55 } }] },
  { id: "espatula-alginato", std: "Espátula Plástica para Alginato", cat: "Instrumental", kw: ["alginato", "plastica"],
    brands: [{ name: "Jon", prices: { cremer: 9.9, surya: 8.91, speed: 10.4 } }] },
  { id: "gral-alginato", std: "Gral de Borracha para Alginato", cat: "Instrumental", kw: ["gral", "grau", "alginato"],
    brands: [{ name: "Jon", prices: { cremer: 12.9, surya: 11.61, speed: 13.55 } }] },
  { id: "injetor-elast", std: "Injetor de Elastômero", cat: "Instrumental", kw: ["injetor", "elastomero"],
    brands: [{ name: "Maquira", prices: { cremer: 24.9, surya: 22.41, speed: 26.14 } }, { name: "Jon", prices: { cremer: 16.9, surya: 15.21, speed: 17.75 } }] },
  { id: "dappen", std: "Pote Dappen de Silicone", cat: "Instrumental", kw: ["dappen"],
    brands: [{ name: "Jon", prices: { cremer: 6.9, surya: 6.21, speed: 7.25 } }] },
  { id: "pincel", std: "Pincel para Aplicação", cat: "Instrumental", kw: ["pincel"],
    brands: [{ name: "Tigre", prices: { cremer: 8.9, surya: 8.01, speed: 9.35 } }] },
  { id: "vaselina", std: "Vaselina Sólida", cat: "Material", kw: ["vaselina"],
    brands: [{ name: "Rioquímica", prices: { cremer: 12.9, surya: 11.61, speed: 13.55 } }] },
  { id: "adaptador-cr", std: "Adaptador de Contra-Ângulo para FG", cat: "Instrumental", kw: ["adaptador", "contra"],
    brands: [{ name: "NSK", prices: { cremer: 34.9, surya: 31.41, speed: 36.65 } }] },
  { id: "ponta-diam", std: "Ponta Diamantada (unidade)", cat: "Material", kw: ["ponta", "diamantada"],
    brands: [{ name: "KG Sorensen", prices: { cremer: 6.9, surya: 6.21, speed: 7.25 } }] },
  { id: "maxicut", std: "Broca Maxicut", cat: "Material", kw: ["maxicut", "broca"],
    brands: [{ name: "Edenta", prices: { cremer: 44.9, surya: 40.41, speed: 47.15 } }] },
  { id: "kit-polimento", std: "Kit de Acabamento e Polimento de Provisório", cat: "Material", kw: ["acabamento", "polimento", "provisoria"],
    brands: [{ name: "Edenta", prices: { cremer: 89.9, surya: 80.91, speed: 94.4 } }] },
  { id: "dente-acrilico", std: "Dente de Acrílico para Estudo", cat: "Material", kw: ["dente", "dentes", "acrilico"],
    brands: [{ name: "Pronew", prices: { cremer: 9.9, surya: 8.91, speed: 10.4 } }] },
  { id: "esculpidor", std: "Esculpidor de Hollemback 3S", cat: "Instrumental", kw: ["esculpidor", "hollemback", "hollenback"],
    brands: [{ name: "Millennium", prices: { cremer: 29.9, surya: 26.91, speed: 31.39 } }] },
  { id: "sonda-endo", std: "Sonda Endodôntica", cat: "Instrumental", kw: ["sonda", "endodontica"],
    brands: [{ name: "Rhein", prices: { cremer: 29.9, surya: 26.91, speed: 31.39 } }] },
  { id: "esp-flex-endo", std: "Espátula Flexível para Endodontia", cat: "Instrumental", kw: ["flexivel", "endodontia"],
    brands: [{ name: "Odus", prices: { cremer: 24.9, surya: 22.41, speed: 26.14 } }] },
  { id: "lima-endo", std: "Lima Endodôntica (caixa)", cat: "Material", kw: ["lima"],
    brands: [{ name: "Maillefer", prices: { cremer: 44.9, surya: 40.41, speed: 47.15 } }, { name: "Genérico", prices: { cremer: 24.9, surya: 22.41, speed: 26.14 } }] },
  { id: "gates", std: "Brocas Gates Glidden (kit)", cat: "Material", kw: ["gates", "glidden", "brocas"],
    brands: [{ name: "Maillefer", prices: { cremer: 39.9, surya: 35.91, speed: 41.9 } }] },
  { id: "cone-guta", std: "Cones de Guta-percha (caixa)", cat: "Material", kw: ["guta", "cones"],
    brands: [{ name: "Odous", prices: { cremer: 29.9, surya: 26.91, speed: 31.39 } }, { name: "Tanari", prices: { cremer: 19.9, surya: 17.91, speed: 20.89 } }] },
  { id: "cone-papel", std: "Pontas de Papel Absorvente (caixa)", cat: "Material", kw: ["papel", "absorvente"],
    brands: [{ name: "Tanari", prices: { cremer: 19.9, surya: 17.91, speed: 20.89 } }] },
  { id: "cimento-endo", std: "Cimento Endodôntico (Endofill)", cat: "Material", kw: ["endofill"],
    brands: [{ name: "Dentsply", prices: { cremer: 64.9, surya: 58.41, speed: 68.15 } }] },
  { id: "espacador", std: "Espaçador Digital Endodôntico", cat: "Instrumental", kw: ["espacador"],
    brands: [{ name: "Odus", prices: { cremer: 22.9, surya: 20.61, speed: 24.04 } }] },
  { id: "cond-endo", std: "Condensador Endodôntico", cat: "Instrumental", kw: ["condensador", "endodontico"],
    brands: [{ name: "Odus", prices: { cremer: 34.9, surya: 31.41, speed: 36.65 } }] },
  { id: "tamborel", std: "Tamborel Metálico", cat: "Instrumental", kw: ["tamborel"],
    brands: [{ name: "Golgran", prices: { cremer: 34.9, surya: 31.41, speed: 36.65 } }] },
  { id: "regua-mm", std: "Régua Milimetrada de Aço", cat: "Instrumental", kw: ["regua", "milimetrada"],
    brands: [{ name: "Golgran", prices: { cremer: 16.9, surya: 15.21, speed: 17.75 } }] },
  { id: "seringa", std: "Seringa Hipodérmica Descartável (c/ agulha)", cat: "Material", kw: ["seringa", "hipodermica"],
    brands: [{ name: "BD", prices: { cremer: 1.9, surya: 1.71, speed: 1.99 } }] },
  { id: "alicate-121", std: "Alicate 121", cat: "Instrumental", kw: ["alicate"],
    brands: [{ name: "Golgran", prices: { cremer: 44.9, surya: 40.41, speed: 47.15 } }, { name: "Genérico", prices: { cremer: 29.9, surya: 26.91, speed: 31.39 } }] },
  { id: "microbrush", std: "Aplicador Descartável (Microbrush)", cat: "Material", kw: ["microbrush", "aplicador"],
    brands: [{ name: "KG", prices: { cremer: 19.9, surya: 17.91, speed: 20.89 } }] },
  { id: "pasta-polimento", std: "Pasta para Polimento de Resina", cat: "Material", kw: ["pasta", "polimento"],
    brands: [{ name: "Diamond", prices: { cremer: 34.9, surya: 31.41, speed: 36.65 } }] },
  { id: "porta-dycal", std: "Porta Hidróxido de Cálcio (Porta Dycal)", cat: "Instrumental", kw: ["dycal"],
    brands: [{ name: "Golgran", prices: { cremer: 24.9, surya: 22.41, speed: 26.14 } }] },
  { id: "arco-young", std: "Arco de Young", cat: "Instrumental", kw: ["young"],
    brands: [{ name: "Golgran", prices: { cremer: 19.9, surya: 17.91, speed: 20.89 } }] },
  { id: "perfurador", std: "Perfurador de Lençol (Ainsworth/Ivory)", cat: "Instrumental", kw: ["perfurador", "pergurador", "ainsworth", "ivory"],
    brands: [{ name: "Golgran", prices: { cremer: 89.9, surya: 80.91, speed: 94.4 } }] },
  { id: "porta-grampo", std: "Pinça Porta-Grampo (Palmer)", cat: "Instrumental", kw: ["palmer", "porta"],
    brands: [{ name: "Golgran", prices: { cremer: 79.9, surya: 71.91, speed: 83.9 } }] },
  { id: "grampo", std: "Grampo para Isolamento (aço inox)", cat: "Instrumental", kw: ["grampo"],
    brands: [{ name: "Golgran", prices: { cremer: 12.9, surya: 11.61, speed: 13.55 } }, { name: "Genérico", prices: { cremer: 7.9, surya: 7.11, speed: 8.29 } }] },
  { id: "fio-dental", std: "Fio Dental", cat: "Material", kw: ["fio"],
    brands: [{ name: "Johnson", prices: { cremer: 6.9, surya: 6.21, speed: 7.25 } }] },
  { id: "tira-lixa", std: "Tira de Lixa de Acabamento", cat: "Material", kw: ["tira", "lixa"],
    brands: [{ name: "3M", prices: { cremer: 15.9, surya: 14.31, speed: 16.7 } }, { name: "TDV", prices: { cremer: 12.9, surya: 11.61, speed: 13.55 } }] },
  { id: "cunha", std: "Cunha de Madeira (sortida)", cat: "Material", kw: ["cunha", "madeira"],
    brands: [{ name: "TDV", prices: { cremer: 14.9, surya: 13.41, speed: 15.65 } }] },
  { id: "matriz-fita", std: "Fita Matriz Metálica / Poliéster", cat: "Material", kw: ["fita", "matriz", "poliester"],
    brands: [{ name: "TDV", prices: { cremer: 9.9, surya: 8.91, speed: 10.4 } }] },
  { id: "oculos", std: "Óculos de Proteção", cat: "Material", kw: ["oculos"],
    brands: [{ name: "Verion", prices: { cremer: 14.9, surya: 13.41, speed: 15.65 } }] },
  { id: "casulo", std: "Casulo para Resinas e Adesivos", cat: "Material", kw: ["casulo", "resinas"],
    brands: [{ name: "Maquira", prices: { cremer: 12.9, surya: 11.61, speed: 13.55 } }] },
  { id: "polidor-espiral", std: "Kit de Polidores Espirais Diamantados", cat: "Material", kw: ["polidores", "espirais", "espiral"],
    brands: [{ name: "American Burrs", prices: { cremer: 49.9, surya: 44.91, speed: 52.4 } }] },
  { id: "torno", std: "Torno de Bancada", cat: "Instrumental", kw: ["torno"],
    brands: [{ name: "Tornim", prices: { cremer: null, surya: null, speed: null } }] },
  { id: "macarico", std: "Maçarico", cat: "Instrumental", kw: ["macarico"],
    brands: [{ name: "Blazer", prices: { cremer: null, surya: null, speed: null } }] },
  { id: "condutor-calor", std: "Condutor de Calor Endodôntico", cat: "Instrumental", kw: ["condutor", "calor"],
    brands: [{ name: "Odus", prices: { cremer: 34.9, surya: 31.41, speed: 36.65 } }] },
  { id: "lucas", std: "Instrumento de Lucas (Cureta)", cat: "Instrumental", kw: ["lucas"],
    brands: [{ name: "Millennium", prices: { cremer: 39.9, surya: 35.91, speed: 41.9 } }] },
  { id: "pote-vidro", std: "Pote de Vidro", cat: "Instrumental", kw: ["pote", "vidro"],
    brands: [{ name: "Nevoni", prices: { cremer: 19.9, surya: 17.91, speed: 20.89 } }] },
  { id: "caneta-hidro", std: "Caneta Hidrocor / Marcadora", cat: "Material", kw: ["caneta", "hidrocor"],
    brands: [{ name: "Pilot", prices: { cremer: 4.9, surya: 4.41, speed: 5.15 } }] },
  { id: "esp-cimento", std: "Espátula para Manipulação de Cimentos", cat: "Instrumental", kw: ["manipulacao", "cimentos"],
    brands: [{ name: "Golgran", prices: { cremer: 18.9, surya: 17.01, speed: 19.84 } }] },
  { id: "arco-microcut", std: "Arco Microcut (Porta-Matriz)", cat: "Instrumental", kw: ["microcut"],
    brands: [{ name: "TDV", prices: { cremer: 34.9, surya: 31.41, speed: 36.65 } }] },
  { id: "unimatrix", std: "Kit de Matrizes Unimatrix", cat: "Material", kw: ["unimatrix", "matriz"],
    brands: [{ name: "TDV", prices: { cremer: 29.9, surya: 26.91, speed: 31.39 } }] },
  { id: "fresa", std: "Fresa Multilaminada", cat: "Material", kw: ["fresa"],
    brands: [{ name: "Angelus", prices: { cremer: 24.9, surya: 22.41, speed: 26.14 } }] },
  { id: "broqueiro", std: "Broqueiro de Alumínio", cat: "Instrumental", kw: ["broqueiro"],
    brands: [{ name: "Jon", prices: { cremer: 29.9, surya: 26.91, speed: 31.39 } }] },
  { id: "escova-broca", std: "Escova para Limpar Brocas", cat: "Instrumental", kw: ["escova", "limpar", "brocas"],
    brands: [{ name: "Preven", prices: { cremer: 12.9, surya: 11.61, speed: 13.55 } }] },
  { id: "esp-dupla", std: "Espátula Dupla nº 3051", cat: "Instrumental", kw: ["dupla", "3051"],
    brands: [{ name: "Millennium", prices: { cremer: 24.9, surya: 22.41, speed: 26.14 } }] },
  { id: "calcador", std: "Calcador Duplo nº 3101", cat: "Instrumental", kw: ["calcador"],
    brands: [{ name: "Millennium", prices: { cremer: 26.9, surya: 24.21, speed: 28.25 } }] },
  { id: "alicate-curvar", std: "Alicate de Curvar Lima", cat: "Instrumental", kw: ["alicate", "curvar"],
    brands: [{ name: "Odus", prices: { cremer: 39.9, surya: 35.91, speed: 41.9 } }] },
  { id: "esp-alm", std: "Espátula ALM", cat: "Instrumental", kw: ["espatula", "alm"],
    brands: [{ name: "Millennium", prices: { cremer: 22.9, surya: 20.61, speed: 24.04 } }] },
  { id: "esp-sd2", std: "Espátula SD2", cat: "Instrumental", kw: ["espatula", "sd2"],
    brands: [{ name: "Millennium", prices: { cremer: 23.9, surya: 21.51, speed: 25.09 } }] },
  { id: "rotate-kit", std: "Limas Rotatórias (Rotate Kit)", cat: "Material", kw: ["rotate"],
    brands: [{ name: "VDW", prices: { cremer: 189.9, surya: 170.91, speed: 199.4 } }] },
  { id: "espatula-cera", std: "Espátula para Cera nº 24/36/50", cat: "Instrumental", kw: ["espatula", "36", "50"],
    brands: [{ name: "Duflex", prices: { cremer: 17.9, surya: 16.11, speed: 18.79 } }] },
  { id: "broca-carbide", std: "Broca Carbide 1557/1568/245", cat: "Material", kw: ["broca", "carbide", "1557", "1568", "245"],
    brands: [{ name: "KG Sorensen", prices: { cremer: 29.9, surya: 26.91, speed: 31.39 } }] },
  { id: "broca-esferica", std: "Broca Esférica (baixa rotação)", cat: "Material", kw: ["broca", "esferica", "tungstenio"],
    brands: [{ name: "KG Sorensen", prices: { cremer: 19.9, surya: 17.91, speed: 20.89 } }] },
  { id: "tira-matriz-aco", std: "Tira Matriz de Aço", cat: "Material", kw: ["tira", "aco"],
    brands: [{ name: "TDV", prices: { cremer: 12.9, surya: 11.61, speed: 13.55 } }] },
  { id: "broca-endoz", std: "Broca Endo Z", cat: "Material", kw: ["broca", "endo"],
    brands: [{ name: "Dentsply", prices: { cremer: 39.9, surya: 35.91, speed: 41.9 } }] },

  // --- Biossegurança / EPI ---
  { id: "luva-proc", std: "Luva de Procedimento (caixa c/ 100)", cat: "Biossegurança", kw: ["luva", "luvas", "procedimento"],
    brands: [{ name: "Supermax", prices: { cremer: 29.9, surya: 26.91, speed: 31.4 } }, { name: "Descarpack", prices: { cremer: 24.9, surya: 22.41, speed: 26.15 } }] },
  { id: "luva-cir", std: "Luva Cirúrgica Estéril (par)", cat: "Biossegurança", kw: ["luva", "cirurgica"],
    brands: [{ name: "Maxitex", prices: { cremer: 3.9, surya: 3.51, speed: 4.1 } }] },
  { id: "mascara", std: "Máscara Descartável Tripla (caixa)", cat: "Biossegurança", kw: ["mascara", "tripla"],
    brands: [{ name: "Descarpack", prices: { cremer: 19.9, surya: 17.91, speed: 20.9 } }] },
  { id: "n95", std: "Máscara N95 / PFF2", cat: "Biossegurança", kw: ["n95", "pff2"],
    brands: [{ name: "3M", prices: { cremer: 6.9, surya: 6.21, speed: 7.25 } }] },
  { id: "touca", std: "Touca / Gorro Descartável (pacote)", cat: "Biossegurança", kw: ["touca", "gorro"],
    brands: [{ name: "Talge", prices: { cremer: 14.9, surya: 13.41, speed: 15.65 } }] },
  { id: "avental-desc", std: "Avental / Capote Descartável", cat: "Biossegurança", kw: ["avental", "capote", "jaleco"],
    brands: [{ name: "Talge", prices: { cremer: 9.9, surya: 8.91, speed: 10.4 } }] },
  { id: "prope", std: "Propé Descartável (pacote)", cat: "Biossegurança", kw: ["prope"],
    brands: [{ name: "Talge", prices: { cremer: 12.9, surya: 11.61, speed: 13.55 } }] },
  { id: "campo-desc", std: "Campo Odontológico Descartável", cat: "Biossegurança", kw: ["campo", "campos"],
    brands: [{ name: "Talge", prices: { cremer: 19.9, surya: 17.91, speed: 20.9 } }] },
  { id: "alcool70", std: "Álcool 70% (frasco)", cat: "Biossegurança", kw: ["alcool"],
    brands: [{ name: "Rioquímica", prices: { cremer: 9.9, surya: 8.91, speed: 10.4 } }] },
  { id: "face-shield", std: "Protetor Facial (Face Shield)", cat: "Biossegurança", kw: ["face shield", "protetor facial", "escudo facial"],
    brands: [{ name: "Genérico", prices: { cremer: 19.9, surya: 17.91, speed: 20.9 } }] },

  // --- Anestesia ---
  { id: "carpule", std: "Seringa Carpule para Anestesia (aspiração)", cat: "Instrumental", kw: ["carpule", "seringa carpule"],
    brands: [{ name: "Golgran", prices: { cremer: 44.9, surya: 40.41, speed: 47.15 } }, { name: "Genérico", prices: { cremer: 29.9, surya: 26.91, speed: 31.4 } }] },
  { id: "agulha-curta", std: "Agulha Gengival Curta (caixa)", cat: "Descartável", kw: ["agulha", "gengival", "curta"],
    brands: [{ name: "DFL", prices: { cremer: 24.9, surya: 22.41, speed: 26.15 } }] },
  { id: "agulha-longa", std: "Agulha Gengival Longa (caixa)", cat: "Descartável", kw: ["agulha", "gengival", "longa"],
    brands: [{ name: "DFL", prices: { cremer: 24.9, surya: 22.41, speed: 26.15 } }] },
  { id: "lidocaina", std: "Anestésico Lidocaína 2% c/ Epinefrina (caixa)", cat: "Anestesia", kw: ["anestesico", "lidocaina", "alphacaine", "xylestesin"],
    brands: [{ name: "DFL", prices: { cremer: 39.9, surya: 35.91, speed: 41.9 } }] },
  { id: "mepivacaina", std: "Anestésico Mepivacaína 2% (caixa)", cat: "Anestesia", kw: ["mepivacaina", "mepiadre", "mepivalem"],
    brands: [{ name: "DFL", prices: { cremer: 44.9, surya: 40.41, speed: 47.15 } }] },
  { id: "articaina", std: "Anestésico Articaína 4% (caixa)", cat: "Anestesia", kw: ["articaina"],
    brands: [{ name: "DFL", prices: { cremer: 59.9, surya: 53.91, speed: 62.9 } }] },
  { id: "topico", std: "Anestésico Tópico (Benzocaína)", cat: "Anestesia", kw: ["topico", "benzocaina", "benzotop"],
    brands: [{ name: "DFL", prices: { cremer: 19.9, surya: 17.91, speed: 20.9 } }] },

  // --- Descartáveis / Sucção ---
  { id: "sugador", std: "Sugador de Saliva Descartável (pacote)", cat: "Descartável", kw: ["sugador", "saliva"],
    brands: [{ name: "Maquira", prices: { cremer: 9.9, surya: 8.91, speed: 10.4 } }] },
  { id: "algodao", std: "Rolete / Rolo de Algodão (pacote)", cat: "Descartável", kw: ["rolo", "algodao", "rolete", "roletes"],
    brands: [{ name: "Cremer", prices: { cremer: 9.9, surya: 8.91, speed: 10.4 } }] },
  { id: "gaze", std: "Gaze / Compressa (pacote)", cat: "Descartável", kw: ["gaze", "compressa"],
    brands: [{ name: "Cremer", prices: { cremer: 12.9, surya: 11.61, speed: 13.55 } }] },
  { id: "babador", std: "Babador / Guardanapo Descartável (pacote)", cat: "Descartável", kw: ["babador", "guardanapo"],
    brands: [{ name: "Talge", prices: { cremer: 14.9, surya: 13.41, speed: 15.65 } }] },
  { id: "filme-pvc", std: "Filme PVC para Proteção (rolo)", cat: "Descartável", kw: ["pvc", "insufilm"],
    brands: [{ name: "Wave", prices: { cremer: 9.9, surya: 8.91, speed: 10.4 } }] },

  // --- Radiologia ---
  { id: "filme-rx", std: "Filme Radiográfico Periapical (caixa)", cat: "Radiologia", kw: ["filme", "radiografico", "periapical"],
    brands: [{ name: "Carestream", prices: { cremer: 129.9, surya: 116.91, speed: 136.4 } }] },
  { id: "posicionador", std: "Posicionador Radiográfico (kit)", cat: "Radiologia", kw: ["posicionador", "cinquino"],
    brands: [{ name: "Indusbello", prices: { cremer: 49.9, surya: 44.91, speed: 52.4 } }] },

  // --- Prótese / Laboratório ---
  { id: "cera7", std: "Cera 7 Rosa para Prótese (caixa)", cat: "Prótese", kw: ["cera", "rosa"],
    brands: [{ name: "Lysanda", prices: { cremer: 19.9, surya: 17.91, speed: 20.9 } }] },
  { id: "godiva", std: "Godiva em Bastão / Baixa Fusão", cat: "Prótese", kw: ["godiva", "bastao"],
    brands: [{ name: "Lysanda", prices: { cremer: 19.9, surya: 17.91, speed: 20.9 } }] },
  { id: "gesso-pedra", std: "Gesso Pedra Tipo IV (kg)", cat: "Prótese", kw: ["gesso", "pedra", "durone"],
    brands: [{ name: "Asfer", prices: { cremer: 39.9, surya: 35.91, speed: 41.9 } }] },
  { id: "gesso-comum", std: "Gesso Comum / Paris (kg)", cat: "Prótese", kw: ["gesso", "comum", "paris"],
    brands: [{ name: "Asfer", prices: { cremer: 12.9, surya: 11.61, speed: 13.55 } }] },
  { id: "silicone-cond", std: "Silicone de Condensação (kit)", cat: "Prótese", kw: ["silicone", "condensacao", "zetaplus", "oranwash"],
    brands: [{ name: "Zhermack", prices: { cremer: 89.9, surya: 80.91, speed: 94.4 } }] },
  { id: "silicone-adic", std: "Silicone de Adição (kit)", cat: "Prótese", kw: ["silicone", "adicao", "express"],
    brands: [{ name: "3M", prices: { cremer: 199.9, surya: 179.91, speed: 209.9 } }] },
  { id: "lecron", std: "Espátula Lecron", cat: "Instrumental", kw: ["lecron"],
    brands: [{ name: "Duflex", prices: { cremer: 19.9, surya: 17.91, speed: 20.9 } }] },

  // --- Periodontia ---
  { id: "cureta-gracey", std: "Cureta Gracey (par)", cat: "Instrumental", kw: ["cureta", "gracey"],
    brands: [{ name: "Golgran", prices: { cremer: 44.9, surya: 40.41, speed: 47.15 } }, { name: "Trinity", prices: { cremer: 29.9, surya: 26.91, speed: 31.4 } }] },
  { id: "cureta-mccall", std: "Cureta McCall", cat: "Instrumental", kw: ["cureta", "mccall"],
    brands: [{ name: "Golgran", prices: { cremer: 39.9, surya: 35.91, speed: 41.9 } }] },
  { id: "foice", std: "Foice / Raspador Periodontal (Ball)", cat: "Instrumental", kw: ["foice", "raspador", "ball"],
    brands: [{ name: "Golgran", prices: { cremer: 29.9, surya: 26.91, speed: 31.4 } }] },
  { id: "cinzel", std: "Cinzel de Wedelstaedt", cat: "Instrumental", kw: ["cinzel", "wedelstaedt"],
    brands: [{ name: "Golgran", prices: { cremer: 34.9, surya: 31.41, speed: 36.65 } }] },
  { id: "arkansas", std: "Pedra de Arkansas (afiar curetas)", cat: "Instrumental", kw: ["arkansas", "afiar"],
    brands: [{ name: "Trinity", prices: { cremer: 24.9, surya: 22.41, speed: 26.15 } }] },

  // --- Cirurgia ---
  { id: "lamina-15", std: "Lâmina de Bisturi nº 15 (caixa)", cat: "Descartável", kw: ["lamina", "15", "15c"],
    brands: [{ name: "Solidor", prices: { cremer: 19.9, surya: 17.91, speed: 20.9 } }] },
  { id: "alavanca-apical", std: "Alavanca Apical Reta", cat: "Instrumental", kw: ["alavanca", "apical"],
    brands: [{ name: "Quinelato", prices: { cremer: 39.9, surya: 35.91, speed: 41.9 } }] },
  { id: "afastador-minnesota", std: "Afastador Minnesota", cat: "Instrumental", kw: ["afastador", "minnesota"],
    brands: [{ name: "Golgran", prices: { cremer: 34.9, surya: 31.41, speed: 36.65 } }] },
  { id: "afastador-farabeuf", std: "Afastador Farabeuf", cat: "Instrumental", kw: ["afastador", "farabeuf"],
    brands: [{ name: "Golgran", prices: { cremer: 34.9, surya: 31.41, speed: 36.65 } }] },
  { id: "mosquito", std: "Pinça Hemostática Mosquito (Kelly)", cat: "Instrumental", kw: ["mosquito", "kelly", "hemostatica"],
    brands: [{ name: "Golgran", prices: { cremer: 29.9, surya: 26.91, speed: 31.4 } }] },
  { id: "backhaus", std: "Pinça Backhaus (fixa campo)", cat: "Instrumental", kw: ["backhaus"],
    brands: [{ name: "Golgran", prices: { cremer: 29.9, surya: 26.91, speed: 31.4 } }] },
  { id: "cuba-inox", std: "Cuba / Cúpula Inox para Antissepsia", cat: "Instrumental", kw: ["cuba", "cupula"],
    brands: [{ name: "Golgran", prices: { cremer: 14.9, surya: 13.41, speed: 15.65 } }] },
  { id: "forceps-151", std: "Fórceps nº 151 (adulto inferior)", cat: "Instrumental", kw: ["forceps", "151"],
    brands: [{ name: "Quinelato", prices: { cremer: 74.9, surya: 67.41, speed: 78.65 } }] },
  { id: "forceps-18", std: "Fórceps nº 18L / 18R (molar superior)", cat: "Instrumental", kw: ["forceps", "18", "18l", "18r"],
    brands: [{ name: "Quinelato", prices: { cremer: 74.9, surya: 67.41, speed: 78.65 } }] },

  // --- Profilaxia / Dentística (materiais) ---
  { id: "taca-borracha", std: "Taça de Borracha para Profilaxia", cat: "Material", kw: ["taca", "profilaxia"],
    brands: [{ name: "TDV", prices: { cremer: 4.9, surya: 4.41, speed: 5.15 } }] },
  { id: "escova-robinson", std: "Escova de Robinson (Profilaxia)", cat: "Material", kw: ["robinson"],
    brands: [{ name: "TDV", prices: { cremer: 3.9, surya: 3.51, speed: 4.1 } }] },
  { id: "pasta-profi", std: "Pasta Profilática", cat: "Material", kw: ["pasta", "profilatica"],
    brands: [{ name: "Maquira", prices: { cremer: 19.9, surya: 17.91, speed: 20.9 } }] },
  { id: "hidroxido", std: "Hidróxido de Cálcio (Dycal / Hydro C)", cat: "Material", kw: ["hidroxido", "dycal", "hydro"],
    brands: [{ name: "Dentsply", prices: { cremer: 44.9, surya: 40.41, speed: 47.15 } }, { name: "Maquira", prices: { cremer: 24.9, surya: 22.41, speed: 26.15 } }] },
  { id: "irm", std: "Óxido de Zinco e Eugenol / IRM (provisório)", cat: "Material", kw: ["irm", "eugenol", "zinco"],
    brands: [{ name: "Dentsply", prices: { cremer: 44.9, surya: 40.41, speed: 47.15 } }] },
  { id: "verniz", std: "Verniz Cavitário", cat: "Material", kw: ["verniz", "cavitario"],
    brands: [{ name: "Coltene", prices: { cremer: 24.9, surya: 22.41, speed: 26.15 } }] },
  { id: "resina-flow", std: "Resina Composta Flow (fluida)", cat: "Material", kw: ["resina", "flow", "fluida"],
    brands: [{ name: "FGM", prices: { cremer: 79.9, surya: 71.91, speed: 83.9 } }, { name: "3M", prices: { cremer: 99.9, surya: 89.91, speed: 104.9 } }] },
  { id: "fotopolimerizador", std: "Fotopolimerizador LED", cat: "Instrumental", kw: ["fotopolimerizador", "fotopolimerizadora", "led"],
    brands: [{ name: "DB", prices: { cremer: 189.9, surya: 170.91, speed: 199.4 } }] },

  // --- Endodontia (soluções e limas) / Moldagem ---
  { id: "hipoclorito", std: "Hipoclorito de Sódio (irrigação)", cat: "Material", kw: ["hipoclorito"],
    brands: [{ name: "Asfer", prices: { cremer: 12.9, surya: 11.61, speed: 13.55 } }] },
  { id: "edta", std: "EDTA (líquido/gel endodôntico)", cat: "Material", kw: ["edta"],
    brands: [{ name: "Biodinâmica", prices: { cremer: 24.9, surya: 22.41, speed: 26.15 } }] },
  { id: "clorexidina", std: "Clorexidina 2% (irrigação)", cat: "Material", kw: ["clorexidina"],
    brands: [{ name: "Rioquímica", prices: { cremer: 14.9, surya: 13.41, speed: 15.65 } }] },
  { id: "hedstroem", std: "Lima Hedströem (caixa)", cat: "Material", kw: ["hedstroem", "hedstrom", "hedstroen"],
    brands: [{ name: "Maillefer", prices: { cremer: 44.9, surya: 40.41, speed: 47.15 } }, { name: "Genérico", prices: { cremer: 24.9, surya: 22.41, speed: 26.15 } }] },
  { id: "mta", std: "MTA / Cimento Reparador", cat: "Material", kw: ["mta"],
    brands: [{ name: "Angelus", prices: { cremer: 149.9, surya: 134.91, speed: 157.4 } }] },
  { id: "alginato-po", std: "Alginato (pó para moldagem)", cat: "Material", kw: ["alginato", "hidrogum", "jeltrate", "orthoprint"],
    brands: [{ name: "Zhermack", prices: { cremer: 29.9, surya: 26.91, speed: 31.4 } }, { name: "Dentsply", prices: { cremer: 39.9, surya: 35.91, speed: 41.9 } }] },
];

export const SAMPLE = `1 espelho bucal n5
cabo p/ espelho
sonda exploradora n5
sonda periodontal williams
pinça clinica
espatula de inserção n1 (thompson)
espatula p/ resina suprafill
escavador / colher de dentina 17
condensador de amalgama
porta matriz tofflemire
cabo de bisturi n3
porta agulha mayo hegar
tesoura iris reta
alavanca seldin 2
forceps 150
destaca periosteo molt
placa de vidro
resina z350 A2
ionomero de vidro restaurador
adesivo single bond
acido fosforico 37%
kit de brocas diamantadas
lençol de borracha (dique)
discos sof-lex
fio de sutura seda 4-0`;

// Troca o catálogo ativo em runtime (do backend). Como CATALOG é `let` exportado,
// os consumidores que leem no momento do uso passam a enxergar o novo catálogo.
export function replaceCatalog(items) {
  if (Array.isArray(items) && items.length) CATALOG = items;
}

